  <div id="SectionContainer">
    <h1>Carepal</h1>
    <p>For the kids who have to live with cystic fibrosis</p>
  </div>
  <div class="content">
    <p>Carepal is a game for 6-8 year olds who live with cystic fibrosis.  It is designed to be educational, entertaining and comforting.  Over the course of four weeks, our team worked with our client to understand what they were looking for, and built a prototype of the game that could run on Android tablets and that kids could test. We learned Unity3D from scratch, managed our scope, communicated it all with our client, and were very successful.</p>
    <div class="center"><img src="/assets/articles/carepal/room.jpg"></div>
    <p>Cystic Fibrosis has many detrimental effects on the body, including difficulty digesting food and absorbing nutrients, chronic respiratory infections, shortness of breath, and even a form of diabetes.  Kids have a hard time understanding the treatments because they’re long-term and there isn’t immediate feedback that the treatments are making them better.  The vision for the game is to take care of your pal Rocky, by playing various minigames related to the treatments and make healthy choices to keep Rocky happy.</p>
    <p>4 weeks really isn’t very much time.  In addition, we didn’t have any experience in Unity3D beforehand. Thankfully, it turned out that a lot of Unity3D is very accessible, plus there’s a vast collection of tutorials and support materials out there in the community.  All it really took was learning the Unity3D way of doing things: build via design tools rather than programmatically, and attach control scripts on objects rather than having a single master controller. The rest was simple!</p>
    <div class="center"><img src="/assets/articles/carepal/fridge.jpg"></div>
    <p>We decided to focus on a single minigame where you get to build your own sandwich.  From the fridge you have to pick out a vegetable, a fat, and a meat, and then you play a Plinko-inspired game where you bounce an olive over pins to hit your favorite toppings.  You can make some pretty monstrous and silly sandwiches and it’s surprisingly fun!</p>
    <div class="center"><img src="/assets/articles/carepal/sandwichgame.jpg"></div>
    <p>My focus during this project was on the art assets.  I actually built the bedroom and fridge in 3D before rendering and manipulating them into cartoon versions.  I spent a great deal of time in image editing software and doing Google image searches to find materials to use.  Since this is an unreleased prototype, not-for-profit, and made for both educational and research purposes, my use of some copyright materials is fair dealing. </p>
    <div class="center"><img src="/assets/articles/carepal/artMap.jpg"></div>
    <p>Outside of the art, I build the fridge food-selecting mini-minigame, set up the camera movement, hooked up animation on the clock and Rocky, and made the bedroom interaction.  Plus testing and bug fixes of course.</p>
    <p>The next step for this project is to implement the reward system. The idea is that when Rocky completes a minigame he earns stars with which he can buy accessories for his room, such as other clothes in his wardrobe.   So rewards and customization come next.  Also more minigames, for example our client has breathing hardware that cystic fibrosis patients use for their breathing exercises, and we could plug that into the game, directly relating game rewards to the kids’ treatments.</p>
    <p>Another exciting and important possibility is letting kids visit other kids rooms online including whatever special customizations they have.  You see when the kids visit the hospital they stay for 2 weeks at a time but they can’t visit with other kids because of their weakened immune systems. Being able to visit in the game will make the condition less isolating and more engaging.</p>
    <p>Carepal source code is available on <a href="https://github.com/IceBlockers/Carepal">GitHub</a>.</p>
  <div class="endFloat">&nbsp;</div></div>
